# -*- makefile -*-
#
# Copyright (c) 2015 Intel, Inc.  All rights reserved.
# Copyright (c) 2016 Cisco Systems, Inc.  All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

sources += \
        src/common/pmix_common.c
