/*
 * Copyright (c) 2015 Cisco Systems, Inc.  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#ifndef OPAL_DL_DLOPEN
#define OPAL_DL_DLOPEN

#include "pmix_config.h"

#include "pmix/mca/dl/dl.h"

OPAL_DECLSPEC extern pmix_dl_base_module_t pmix_dl_dlopen_module;

/*
 * Dynamic library handles generated by this component.
 *
 * If we're debugging, keep a copy of the name of the file we've opened.
 */
struct pmix_dl_handle_t {
    void *dlopen_handle;
#if OPAL_ENABLE_DEBUG
    void *filename;
#endif
};

typedef struct {
    pmix_dl_base_component_t base;

    char *filename_suffixes_mca_storage;
    char **filename_suffixes;
} pmix_dl_dlopen_component_t;

OPAL_DECLSPEC extern pmix_dl_dlopen_component_t mca_dl_dlopen_component;

#endif /* OPAL_DL_DLOPEN */
